game_id = "45"
comparator = "2"
condition_id = "1"
suit = "0"
value = "3"

[player_1]
name = "Bob"
card1_suit = "1"
card1_value = "5"
card2_suit = "2"
card2_value = "5"
card3_suit = "3"
card3_value = "5"
condition_choice = "1"
challenge_choice = "0"

[player_2]
name = "Alice"
card1_suit = "2"
card1_value = "6"
card2_suit = "3"
card2_value = "7"
card3_suit = "4"
card3_value = "8"
condition_choice = "0"
challenge_choice = "1"
