_game_id = "50"
comparator = "2"
condition_id = "1"
hand_commitment = "0x2635b719bd7abba9690154ecb34623a366761602b218e704d623d51b534e3212"
suit = "0"
value = "3"

[hand]
card1_suit = "2"
card1_value = "11"
card2_suit = "3"
card2_value = "3"
card3_suit = "4"
card3_value = "9"
