_game_id = "16"
comparator = "0"
condition_id = "16"
hand_commitment = "0x1722567aaeb8c868b218fd87d8cc5d15a9823b55501321d4cb0d1b8a3c3d583f"
suit = "0"
value = "0"

[hand]
card1_suit = "2"
card1_value = "1"
card2_suit = "3"
card2_value = "2"
card3_suit = "4"
card3_value = "3"
