_game_id = "45"
comparator = "2"
condition_id = "1"
hand_commitment = "0x1a4ef6d0abb0463e0f576447476e4f5ba4734d605bbb3e8754639a205876004c"
suit = "0"
value = "3"

[hand]
card1_suit = "2"
card1_value = "6"
card2_suit = "3"
card2_value = "7"
card3_suit = "4"
card3_value = "8"
