world_address = "0x05f37ff49cd03dee4eea16212250251c875d2631e6e7bc64d1c3ddf44753873b"

rpc = "https://ztarknet-madara.d.karnot.xyz"

[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]
[sql]
historical = []

